<a href="https://colab.research.google.com/github/anitayadav3/EmotionRecognitionInConversation/blob/master/DialogueRNN_IEMOCAP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install torch_sparse

  Created wheel for torch-sparse: filename=torch_sparse-0.6.7-cp36-cp36m-linux_x86_64.whl size=22081958 sha256=8105c619f018190eb6d16d67beb23788e97b54f1501200c719f55da3c63c7efa
  Stored in directory: /root/.cache/pip/wheels/56/54/57/495938ad744a865b8933e76fa71853495f2ac476475d49a9a2
Successfully built torch-sparse


In [3]:
!pip install torch_scatter

  Using cached https://files.pythonhosted.org/packages/01/45/cd93ed3227248773ba8bc4b3beaa04e8bddb127a793a41bad875369951b3/torch_scatter-2.0.5.tar.gz
  Created wheel for torch-scatter: filename=torch_scatter-2.0.5-cp36-cp36m-linux_x86_64.whl size=11359446 sha256=2e5b27c3a951eb3f5c82e93a307ab2ccd5a0317c437d2bc2a5ea87b5d66129a8
  Stored in directory: /root/.cache/pip/wheels/42/59/d3/9866e4fd8e1fe9260740acfe22322c428bc0dc064d3ebc456c
Successfully built torch-scatter


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
%cd /content/drive/My Drive/DialogueRNN

/content/drive/My Drive/DialogueRNN


In [ ]:
#!python train_IEMOCAP.py --dropout 0.4 --lr 0.0003 --batch-size 32 --class-weight --l2 0.0

In [4]:
import numpy as np
np.random.seed(1234)
import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from torch.utils.data.sampler import SubsetRandomSampler
import torch.optim as optim
import argparse
import time
import pickle
from sklearn.metrics import f1_score, confusion_matrix, accuracy_score,\
                        classification_report, precision_recall_fscore_support
from model import BiModel, Model, MaskedNLLLoss
from dataloader import IEMOCAPDataset

In [5]:
def get_train_valid_sampler(trainset, valid=0.1):
    size = len(trainset)
    idx = list(range(size))
    split = int(valid*size)
    return SubsetRandomSampler(idx[split:]), SubsetRandomSampler(idx[:split])

def get_IEMOCAP_loaders(path, batch_size=32, valid=0.1, num_workers=0, pin_memory=False):
    trainset = IEMOCAPDataset(path=path)
    train_sampler, valid_sampler = get_train_valid_sampler(trainset, valid)
    train_loader = DataLoader(trainset,
                              batch_size=batch_size,
                              sampler=train_sampler,
                              collate_fn=trainset.collate_fn,
                              num_workers=num_workers,
                              pin_memory=pin_memory)
    valid_loader = DataLoader(trainset,
                              batch_size=batch_size,
                              sampler=valid_sampler,
                              collate_fn=trainset.collate_fn,
                              num_workers=num_workers,
                              pin_memory=pin_memory)

    testset = IEMOCAPDataset(path=path, train=False)
    test_loader = DataLoader(testset,
                             batch_size=batch_size,
                             collate_fn=testset.collate_fn,
                             num_workers=num_workers,
                             pin_memory=pin_memory)

    return train_loader, valid_loader, test_loader

def train_or_eval_model(model, loss_function, dataloader, epoch, optimizer=None, train=False):
    losses = []
    preds = []
    labels = []
    masks = []
    alphas, alphas_f, alphas_b, vids = [], [], [], []
    assert not train or optimizer!=None
    if train:
        model.train()
    else:
        model.eval()
    for data in dataloader:
        if train:
            optimizer.zero_grad()
        # import ipdb;ipdb.set_trace()
        textf, visuf, acouf, qmask, umask, label =\
                [d.cuda() for d in data[:-1]] if cuda else data[:-1]
        #log_prob = model(torch.cat((textf,acouf,visuf),dim=-1), qmask,umask,att2=True) # seq_len, batch, n_classes
        log_prob, alpha, alpha_f, alpha_b = model(textf, qmask,umask,att2=True) # seq_len, batch, n_classes
        lp_ = log_prob.transpose(0,1).contiguous().view(-1,log_prob.size()[2]) # batch*seq_len, n_classes
        labels_ = label.view(-1) # batch*seq_len
        loss = loss_function(lp_, labels_, umask)

        pred_ = torch.argmax(lp_,1) # batch*seq_len
        preds.append(pred_.data.cpu().numpy())
        labels.append(labels_.data.cpu().numpy())
        masks.append(umask.view(-1).cpu().numpy())

        losses.append(loss.item()*masks[-1].sum())
        if train:
            loss.backward()
            if args.tensorboard:
                for param in model.named_parameters():
                    writer.add_histogram(param[0], param[1].grad, epoch)
            optimizer.step()
        else:
            alphas += alpha
            alphas_f += alpha_f
            alphas_b += alpha_b
            vids += data[-1]

    if preds!=[]:
        preds  = np.concatenate(preds)
        labels = np.concatenate(labels)
        masks  = np.concatenate(masks)
    else:
        return float('nan'), float('nan'), [], [], [], float('nan'),[]

    avg_loss = round(np.sum(losses)/np.sum(masks),4)
    avg_accuracy = round(accuracy_score(labels,preds,sample_weight=masks)*100,2)
    avg_fscore = round(f1_score(labels,preds,sample_weight=masks,average='weighted')*100,2)
    return avg_loss, avg_accuracy, labels, preds, masks,avg_fscore, [alphas, alphas_f, alphas_b, vids]

In [6]:
batch_size = 32
n_classes  = 6
cuda = torch.cuda.is_available()
n_epochs   = 60

In [7]:
D_m = 100
D_g = 500
D_p = 500
D_e = 300
D_h = 300
D_a = 100 # concat attention

In [8]:
model = BiModel(D_m, D_g, D_p, D_e, D_h,
                n_classes=n_classes,
                listener_state=False,
                context_attention='general',
                dropout_rec=0.1,
                dropout=0.4)

In [9]:
model.cuda()

BiModel(
  (dropout): Dropout(p=0.4, inplace=False)
  (dropout_rec): Dropout(p=0.55, inplace=False)
  (dialog_rnn_f): DialogueRNN(
    (dropout): Dropout(p=0.1, inplace=False)
    (dialogue_cell): DialogueRNNCell(
      (g_cell): GRUCell(600, 500)
      (p_cell): GRUCell(600, 500)
      (e_cell): GRUCell(500, 300)
      (dropout): Dropout(p=0.1, inplace=False)
      (attention): MatchingAttention(
        (transform): Linear(in_features=100, out_features=500, bias=False)
      )
    )
  )
  (dialog_rnn_r): DialogueRNN(
    (dropout): Dropout(p=0.1, inplace=False)
    (dialogue_cell): DialogueRNNCell(
      (g_cell): GRUCell(600, 500)
      (p_cell): GRUCell(600, 500)
      (e_cell): GRUCell(500, 300)
      (dropout): Dropout(p=0.1, inplace=False)
      (attention): MatchingAttention(
        (transform): Linear(in_features=100, out_features=500, bias=False)
      )
    )
  )
  (linear): Linear(in_features=600, out_features=600, bias=True)
  (smax_fc): Linear(in_features=600, out_featur

In [10]:
loss_weights = torch.FloatTensor([
                                    1/0.086747,
                                    1/0.144406,
                                    1/0.227883,
                                    1/0.160585,
                                    1/0.127711,
                                    1/0.252668,
                                      ])

In [11]:
loss_function = MaskedNLLLoss(loss_weights.cuda())

In [12]:
optimizer = optim.Adam(model.parameters(),
                           lr=0.0003,
                           weight_decay=0.0)

In [13]:
train_loader, valid_loader, test_loader =\
            get_IEMOCAP_loaders('./IEMOCAP_features/IEMOCAP_features_raw.pkl',
                                valid=0.0,
                                batch_size=batch_size,
                                num_workers=2)

In [14]:
best_loss, best_label, best_pred, best_mask = None, None, None, None

In [15]:
test_cell = nn.GRUCell(100,100,True)

In [16]:
losses = []
preds = []
labels = []
masks = []
alphas, alphas_f, alphas_b, vids = [], [], [], []

dataloader=train_loader


In [17]:
for data in dataloader:
  optimizer.zero_grad()
  textf, visuf, acouf, qmask, umask, label =\
                [d.cuda() for d in data[:-1]] if cuda else data[:-1]
  log_prob, alpha, alpha_f, alpha_b = model(textf, qmask,umask,att2=True)
  lp_ = log_prob.transpose(0,1).contiguous().view(-1,log_prob.size()[2])
  labels_ = label.view(-1)
  loss = loss_function(lp_, labels_, umask)
  pred_ = torch.argmax(lp_,1)
  preds.append(pred_.data.cpu().numpy())
  labels.append(labels_.data.cpu().numpy())
  masks.append(umask.view(-1).cpu().numpy())
  losses.append(loss.item()*masks[-1].sum())
  loss.backward()
  optimizer.step()

In [18]:
if preds!=[]:
  preds  = np.concatenate(preds)
  labels = np.concatenate(labels)
  masks  = np.concatenate(masks)
else:
  print(float('nan'), float('nan'), [], [], [], float('nan'),[])

In [19]:
avg_loss = round(np.sum(losses)/np.sum(masks),4)
avg_accuracy = round(accuracy_score(labels,preds,sample_weight=masks)*100,2)
avg_fscore = round(f1_score(labels,preds,sample_weight=masks,average='weighted')*100,2)

In [20]:
print(avg_loss)
print(avg_accuracy)
print(labels)
print(preds)
print(masks)
print(avg_fscore)
print([alphas, alphas_f, alphas_b, vids])

1.6767
33.86
[2 4 5 ... 0 0 0]
[3 4 4 ... 4 4 4]
[1. 1. 1. ... 0. 0. 0.]
31.28
[[], [], [], []]
